export type ResearchCategory = "Saham" | "Makro & Kebijakan" | "Komoditas" | "Global";

export type ResearchIssue = {
  number: number;
  title: string;
  fileId: string;
  uploadedAt: string;
  publishedAt: string | null;
  category: ResearchCategory;
  summary: string[] | null;
  tickers: string[];
};

// Dates and summaries come from PDF text, when readable. Upload timestamps are
// Google Drive metadata and must not be presented as publication dates.
export const MERIDIAN_ISSUES: ResearchIssue[] = [
  { number: 25, title: "Gocap & Credit", fileId: "1ZMGnkUYYDj-Ejpl4ATioomXJ60NVoX-7", uploadedAt: "2026-09-30", publishedAt: "2026-09-27", category: "Makro & Kebijakan", tickers: ["GOTO"], summary: ["Saham di kisaran Rp50–60 berjumlah banyak, tetapi dalam perhitungan Meridian hanya mencakup sekitar 1,1% kapitalisasi IHSG. Pelemahan saham besar lebih menentukan arah indeks.", "Kredit investasi tumbuh lebih cepat daripada simpanan. Meridian menilai tekanan margin bank dan dukungan likuiditas pemerintah perlu dipantau, bukan menyamakan pertumbuhan kredit dengan pemulihan konsumsi luas."] },
  { number: 24, title: "ADMR & Bioethanol", fileId: "1d3vac2hG8hSy0xfYhrlaw3MGxr0uajjs", uploadedAt: "2026-09-20", publishedAt: "2026-09-20", category: "Saham", tickers: ["ADMR", "SRSN", "MOLI"], summary: ["Laba 1H26 ADMR tertinggal dari ekspektasi saat biaya peleburan aluminium sudah muncul sebelum penjualan. Laporan menempatkan pengiriman dan konversi persediaan menjadi pendapatan sebagai uji utama berikutnya.", "Target campuran bioetanol menghadapi keterbatasan tebu, pabrik, dan harga acuan. Meridian menyebut SRSN dan MOLI sebagai emiten yang perlu dipantau alokasi pasokan serta belanja kapasitasnya, bukan menganggap mandat otomatis menjadi laba."] },
  { number: 23, title: "Foreign Flow & DSI", fileId: "1n6GtL3K0TDDwM7d5YRYCsqA3GbsuLPov", uploadedAt: "2026-09-13", publishedAt: "2026-09-13", category: "Makro & Kebijakan", tickers: ["ANTM", "MDKA", "INDF", "BBCA", "BBRI", "BMRI"], summary: ["Tekanan jual asing pada LQ45 mereda sepanjang Agustus 2026, tetapi pembelian masih selektif. Laporan menyorot saham komoditas dan INDF; bank besar masih berpeluang menerima aliran dana jika pemulihan meluas.", "Bagian DSI membandingkan selisih data ekspor CPO dan batu bara. Meridian menilai dampak tahap pertama belum terlihat jelas dan mandat ekspor langsung mulai 2027 akan menjadi ujian berikutnya."] },
  { number: 22, title: "Coal & Data Center", fileId: "1a-PyWDyjoFy7JGfI-yaG02Dh-7SpI9L0", uploadedAt: "2026-09-12", publishedAt: "2026-09-06", category: "Komoditas", tickers: ["DMAS", "BEST", "KIJA", "POWR", "TOTL", "ISAT"], summary: ["Meridian menilai pembatasan pasokan batu bara Tiongkok dan ketidakpastian ekspor Indonesia dapat menopang pasar jangka pendek; dampaknya berbeda menurut kemampuan tiap produsen menjual ke pasar ekspor.", "Untuk tema pusat data, laporan menyorot DMAS dan BEST yang sudah memiliki kampus berpenghuni, serta KIJA, POWR, TOTL, dan ISAT pada infrastruktur tenaga dan konektivitas. Keterlambatan pasokan listrik menjadi risiko utama."] },
  { number: 21, title: "Zankore & Automotive Revival", fileId: "12872Oi13fCU4LT2prg6mqnJr0uDKg-X4", uploadedAt: "2026-09-02", publishedAt: "2026-08-30", category: "Saham", tickers: ["ISAT"], summary: ["ISAT mengembangkan NeoCloud dan usaha patungan pusat data AI Zankore. Meridian menilai potensi laba bergantung pada jadwal pembangunan, tingkat pemakaian, dan biaya pendanaan; kontribusi saat ini belum menjadi bisnis utama.", "Kenaikan penjualan grosir mobil pada 2026 bisa dipengaruhi pengisian stok dealer. Laporan menggunakan penjualan sepeda motor dan realisasi pabrik EV sebagai penguji kekuatan permintaan konsumen."] },
  { number: 19, title: "CPO & Danantara WtE", fileId: "1bUd-4NCxiqCYyUTQwj4i2HhmogQWAhGD", uploadedAt: "2026-08-22", publishedAt: "2026-08-16", category: "Komoditas", tickers: ["OASA", "BIPI", "IMPC", "SOFA"], summary: ["Pasokan CPO 2026 pulih, tetapi pertumbuhan produksi Indonesia dan Malaysia semakin terbatas. Risiko El Niño dapat memperketat pasar 2027; ini tesis komoditas, bukan otomatis untuk semua saham perkebunan.", "Program waste-to-energy Danantara membuka skema tarif dan pembiayaan baru. Meridian membedakan OASA yang memiliki proyek operasional dari emiten lain yang baru terkait tema atau proses tender; partisipasi perlu diverifikasi per perusahaan."] },
  { number: 18, title: "Copper & INCO", fileId: "1nJmzlxe_vnnlQR9B-MQjJ1V5FonorTcR", uploadedAt: "2026-08-15", publishedAt: "2026-08-09", category: "Komoditas", tickers: ["INCO"], summary: ["Meridian menilai harga tembaga tampak mahal menurut beberapa model makro, tetapi stok fisik yang turun dan gangguan pasokan tambang dapat mempertahankan pasar ketat lebih lama.", "INCO menunjukkan perbaikan produksi dan penjualan bijih pada 2Q26. Persetujuan revisi RKAB dan realisasi proyek smelter tetap menjadi penentu utama tesis laba berikutnya."] },
  { number: 17, title: "Market Gaps & BI", fileId: "1QU6BTx4SDprHQdIR1nhBBTeeikXhhu7e", uploadedAt: "2026-08-15", publishedAt: "2026-08-02", category: "Makro & Kebijakan", tickers: [], summary: ["Meridian mengamati tingkat penutupan gap historis IHSG yang tinggi, tetapi waktu menunggu dan biaya peluang tetap penting. Pola historis tidak memastikan gap saat ini akan tertutup dalam waktu tertentu.", "Bagian BI membahas dampak pergantian kepemimpinan terhadap kepercayaan terhadap kebijakan dan rupiah. Angka 2,47% dalam laporan merupakan estimasi riset, bukan kurs atau dampak yang dapat dipastikan."] },
  { number: 14, title: "US Edition 2.0", fileId: "1JczdPpB1j3y5-hnbvDl71X2aQIwiDNmI", uploadedAt: "2026-07-14", publishedAt: "2026-07-12", category: "Global", tickers: ["AMD", "LLY"], summary: ["Meridian menyorot pangsa pasar CPU dan pertumbuhan pusat data AMD, dengan risiko penundaan produk serta biaya memori GPU. Tesisnya bergantung pada eksekusi, bukan sekadar mengejar Nvidia.", "Laporan mengaitkan pertumbuhan Eli Lilly dengan penjualan Mounjaro dan pasar obat obesitas internasional. Ekspansi di negara berkembang dinilai peluang jangka panjang, dengan risiko harga dan akses pasien."] },
  { number: 13, title: "US Edition", fileId: "1dLCHWOwy6TGwiCWZg5j99lnMvBoIGLTU", uploadedAt: "2026-07-06", publishedAt: "2026-07-05", category: "Global", tickers: ["GLW", "INTC", "AMD"], summary: ["Surat ini membahas pergeseran belanja AI dari pelatihan model ke inference dan jaringan optik. Corning (GLW) diposisikan pada permintaan serat optik pusat data; perlambatan belanja hyperscaler menjadi risiko.", "Intel dibahas sebagai tesis pemulihan berisiko tinggi yang bergantung pada eksekusi foundry. AMD disebut sebagai pembanding dengan posisi CPU yang lebih kuat; laporan menekankan ukuran posisi dan horizon lebih panjang."] },
  { number: 12, title: "Fiscal & IHSG", fileId: "1eTIQB8AMNlaPcNSTcN24wEYe2k14qBQV", uploadedAt: "2026-06-28", publishedAt: "2026-06-28", category: "Makro & Kebijakan", tickers: [], summary: ["Meridian menilai tiga pos besar—makan bergizi gratis, pertahanan, dan subsidi—membatasi ruang fiskal ketika penerimaan pajak belum mengejar pengeluaran. Penerbitan utang dan kurs rupiah menjadi indikator risiko yang disarankan untuk dipantau.", "Laporan memberi skenario bearish IHSG dari model turunan harga dan sejarah drawdown menuju sekitar 4.000. Itu proyeksi penulis dengan ketidakpastian tinggi, bukan target harga yang sudah terjadi. Penulis lebih positif pada saham AS dan menghindari IHSG saat itu."] },
  { number: 11, title: "TINS & Duration Trap", fileId: "1LJNo2QPF_HyDl8rl7BcxiJmyvNyRG7D2", uploadedAt: "2026-06-21", publishedAt: "2026-06-21", category: "Saham", tickers: ["TINS"], summary: ["Meridian menilai kenaikan TINS bukan hanya akibat harga timah: penertiban tambang dan peleburan ilegal bertepatan dengan kenaikan pangsa ekspor serta laba kuartal pertama. Data ekspor bulan berikutnya menjadi penguji apakah perubahan itu bertahan.", "Bagian duration trap menilai perusahaan mapan dapat memberi imbal hasil lebih rendah saat peluang investasi ulang menyusut. Meridian tetap berhati-hati terhadap IHSG dan menekankan bahwa pertumbuhan laba TINS belum menghilangkan risiko izin ekspor dan harga komoditas."] },
  { number: 10, title: "KopDes & IHSG", fileId: "1EY7GabP5B_TN2VQZy3Gap7J0-FUoiMCq", uploadedAt: "2026-06-14", publishedAt: "2026-06-14", category: "Makro & Kebijakan", tickers: ["AMRT", "BREN", "DSSA"], summary: ["Meridian menilai KopDes Merah Putih berpotensi bersaing dengan AMRT di daerah rural, tetapi data operasional pada 14 Juni 2026 belum menunjukkan ekspansi besar di luar Jawa. Jumlah unit aktif di luar Jawa menjadi indikator utama apakah tekanan bagi AMRT bersifat struktural.", "Bagian IHSG berubah lebih positif secara taktis, sambil membatasi eksposur Indonesia karena rezim pasar dinilai belum mudah diprediksi. BREN dan DSSA muncul dalam daftar posisi yang disukai penulis saat itu."] },
  { number: 9, title: "Credit Rating & MSCI", fileId: "1Y0y-Wxd9AxbzbTKXOCRC22c5AFWQMgDR", uploadedAt: "2026-06-07", publishedAt: "2026-06-07", category: "Makro & Kebijakan", tickers: ["BBCA", "BBRI", "BMRI", "BBNI"], summary: ["Riset ini membedakan perubahan outlook kredit negara dari penurunan rating. Dalam contoh historis yang dipakai Meridian, tekanan pasar saham lebih besar ketika outlook memburuk sebelum keputusan rating resmi.", "Meridian menyusun tiga skenario klasifikasi MSCI Indonesia, lalu membahas risiko bank besar melalui analisis teknikal. Skenario aliran dana dan gelombang harga tersebut adalah pandangan pada tanggal laporan, bukan hasil yang sudah terkonfirmasi."] },
  { number: 8, title: "Index Anchor & GOTO", fileId: "1dEsnf1CGw4I_WKTMqsQiy1OmzK0F3YMy", uploadedAt: "2026-05-31", publishedAt: "2026-05-31", category: "Saham", tickers: ["BREN", "DSSA", "TPIA", "BBCA", "GOTO"], summary: ["Meridian menilai penggerak IHSG bergeser dari kelompok saham spekulatif seperti BREN, DSSA, dan TPIA ke bank besar. Pergeseran itu dinilai bisa mengurangi partisipasi pasar luas ketika bank menghadapi tekanan arus asing dan kurs.", "GOTO dibahas setelah laba kuartalan pertamanya, bersamaan dengan risiko pembatasan komisi menjadi 8%, saham di batas Rp50, dan peninjauan likuiditas MSCI. Rencana biaya tambahan per perjalanan dalam laporan masih berupa asumsi yang perlu diuji terhadap perilaku pengguna."] },
  { number: 7, title: "Gold & DSI", fileId: "1nt7j7steVHqICXvu5OF49wlsMtwhqUS7", uploadedAt: "2026-05-24", publishedAt: "2026-05-24", category: "Komoditas", tickers: [], summary: ["Meridian membedakan prospek emas jangka panjang dari kegunaannya sebagai lindung nilai rupiah jangka pendek. Pada tanggal laporan, penulis menilai imbal hasil riil AS dan dolar yang kuat bisa menekan emas meski pandangan strukturalnya positif.", "Laporan menilai Danantara Sumberdaya Indonesia (DSI) sebagai calon perantara ekspor batu bara, CPO, dan ferroalloy. Risiko yang disorot ialah negosiasi ulang kontrak, tekanan margin produsen, serta kemungkinan pembeli beralih ke pemasok negara lain."] },
  { number: 6, title: "Rupiah DHE & Elliot Wave", fileId: "1Nh50vL_2ZSUDLdryu-SK8-0qKb7njMQ1", uploadedAt: "2026-05-17", publishedAt: "2026-05-17", category: "Makro & Kebijakan", tickers: ["BBCA", "BBRI", "BUMI", "ELSA", "BRPT", "PTRO", "MBMA"], summary: ["Meridian menjelaskan bagaimana kewajiban penempatan Devisa Hasil Ekspor (DHE) dapat menambah likuiditas dolar di dalam negeri, tetapi menilai kebijakan itu sendiri tidak cukup untuk mengatasi tekanan struktural rupiah.", "Bagian Elliott Wave menyajikan skenario teknikal untuk tujuh saham BEI dan ETF EIDO. Penulis menyebutnya jalur probabilitas, bukan kepastian; grafik saham yang ditautkan di sini menampilkan pergerakan harga sejak laporan, bukan validasi pola tersebut."] },
  { number: 5, title: "Royalties & IHSG", fileId: "11NOm7PlOUvzHEqONbd4GKMem9hC2cYBP", uploadedAt: "2026-05-11", publishedAt: "2026-05-10", category: "Makro & Kebijakan", tickers: ["TINS", "ANTM", "INCO", "MBMA", "PTBA", "ADRO", "AADI"], summary: ["Laporan membahas rancangan kenaikan royalti emas, timah, tembaga, dan perak setelah rapat publik ESDM 8 Mei 2026. TINS dan ANTM dinilai paling terekspos; batu bara tidak termasuk rancangan perubahan saat itu. Besaran akhir masih bergantung pada aturan yang disahkan.", "Meridian juga menilai rezim pasar IHSG saat itu kurang memberi imbalan atas pengambilan risiko. Ini adalah pandangan historis penulis, bukan penilaian otomatis atas kondisi pasar terbaru."] },
  { number: 4, title: "IHSG & ICBP", fileId: "1cgA-l_VddhbgUQFuWEFAAhWTWGM0bTOu", uploadedAt: "2026-05-03", publishedAt: "2026-05-03", category: "Saham", tickers: ["ICBP"], summary: ["ICBP tampak murah menurut rasio laba historis, tetapi Meridian menyorot ketahanan margin karena bahan baku impor dan rupiah lemah. Pertumbuhan laba bersih tidak otomatis berarti tekanan biaya operasional sudah selesai.", "Bagian IHSG memakai skenario Elliott Wave dan menilai rebound teknikal belum cukup membuktikan perubahan tren. Penulis menyorot likuiditas, harga minyak, dan tekanan margin bank sebagai risiko pada tanggal laporan."] },
  { number: 3, title: "Rupiah & Ammonia", fileId: "1o6ExXjwiCCJlFc5q5SkXwDKEOdYCKkxN", uploadedAt: "2026-05-03", publishedAt: null, category: "Makro & Kebijakan", tickers: ["ESSA"], summary: ["Meridian membahas tekanan rupiah saat arus dolar domestik dinilai lebih menentukan dibanding sebagian indikator makro konvensional. Penulis mengambil pandangan positif pada USD/IDR pada saat laporan dibuat.", "Gangguan pelayaran Selat Hormuz dan pasokan gas/LNG diperkirakan menaikkan biaya amonia dan urea. ESSA disebut sebagai produsen amonia tercatat yang mungkin diuntungkan setelah pasar pulih, dengan risiko utama jika jalur pasokan kembali normal lebih cepat."] },
  { number: 2, title: "Big Banks & Nickel", fileId: "14prpsOEH51TBNnKRX3V9aksS4E4POuhj", uploadedAt: "2026-05-03", publishedAt: null, category: "Saham", tickers: ["BBCA", "BMRI", "BBRI", "BBNI", "BREN", "CUAN", "ELSA", "INCO", "SRTG"], summary: ["Meridian menilai valuasi bank besar yang tampak murah harus dibandingkan dengan tekanan biaya dana, margin bunga, dan kualitas aset. BBCA, BMRI, BBRI, dan BBNI ditempatkan dalam kelompok yang dihindari pada saat laporan.", "Untuk nikel, kenaikan acuan harga bijih dan asam sulfat berpotensi mempersempit margin operator HPAL yang bergantung pada bahan baku eksternal. INCO disebut pilihan utama penulis di antara pemain nikel terintegrasi; saham lain pada daftar adalah posisi taktis laporan, bukan rekomendasi saat ini."] },
  { number: 1, title: "Hormuz & Sulfuric Acid", fileId: "1Z8_HXyCJop9rZHqrn5l8U9sZlVzPGx9v", uploadedAt: "2026-05-03", publishedAt: null, category: "Komoditas", tickers: ["NCKL", "HRUM", "INCO", "MBMA"], summary: ["Laporan menghubungkan gangguan Selat Hormuz dan pembatasan ekspor asam sulfat Tiongkok dengan risiko biaya bagi pengolahan nikel HPAL. Ketahanan stok asam serta pulihnya jalur pelayaran menjadi variabel yang disorot.", "NCKL dan HRUM disebut dalam kelompok operator yang menghadapi tekanan biaya. INCO dan MBMA dibahas terkait jalur nickel matte; MBMA juga disebut memiliki produksi asam sulfat sendiri. Ini adalah analisis rantai pasok pada tanggal dokumen, bukan kondisi perusahaan terkini."] },
];

export function researchIssue(number: number) { return MERIDIAN_ISSUES.find((issue) => issue.number === number) ?? null; }
export function researchFileUrl(issue: ResearchIssue) { return `https://drive.google.com/file/d/${issue.fileId}/view`; }
export function researchPreviewUrl(issue: ResearchIssue) { return `https://drive.google.com/file/d/${issue.fileId}/preview`; }
export function researchDownloadUrl(issue: ResearchIssue) { return `https://drive.google.com/uc?export=download&id=${issue.fileId}`; }
export function researchTickerUrl(code: string) {
  return ["AMD", "LLY", "GLW", "INTC"].includes(code) ? `https://finance.yahoo.com/quote/${code}/` : `/asset/${code}`;
}
export function researchTickerName(code: string) {
  return ({ AMD: "Advanced Micro Devices", LLY: "Eli Lilly", GLW: "Corning", INTC: "Intel" } as Record<string, string>)[code] ?? null;
}
